package-lock.json, package.json, src/web.ts
I've tried the new version and it didn't work because of the fact that we need to pass true to 
> googleUser.getAuthResponse(true);
otherwise, it won't return accessToken 😕 
Sorry to bother you less I've even bumped the version to 0.0.5, it would mean very much to me if you could accept this and push a new version of the package to npm.
Thank you.
=> For accessToken to be exposed needed to pass param

ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift
This PR ads a signOut method, only implemented on iOS so far, not sure how to implement on web, and Android isn't done yet so I'd rather not touch the code for that.
This is useful for https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/5 for the reasons mentioned there.
=> Add Sign out.

CodetrixStudioCapacitorGoogleAuth.podspec, ios/Podfile
Version 5.0 of the google sign in lib includes breaking changes. For now it's probably best to pin the old version, till this library can be updated.
=> Lock GoogleSignIn version to something compatible with this lib

.gitignore, README.md, android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java, demo/capacitor.config.json, ios/Plugin/Plugin.swift
I've tested it on Android and iOS and works great.
You can then close this issue https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/44
More informations here for Android : 
https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder#public-googlesigninoptions.builder-requestserverauthcode-string-serverclientid,-boolean-forcecodeforrefreshtoken
and here for iOS : 
https://stackoverflow.com/questions/42434887/google-sign-in-server-auth-code-nil-ios
=> Add support for forceAuthCode on iOS and Android

package-lock.json, package.json, src/web.ts
use 'registerPlugin' func instead of using registerWebPlugin
registerWebPlugin function is deprecated.
This PR can be breaking changes for v2.
=> [Capacitor v3] use 'registerPlugin' func instead of using registerWebPlugin

src/definitions.ts, src/index.ts, src/web.ts, tsconfig.json
1. Refactor registering plugins by spec doc 
https://capacitorjs.com/docs/updating/plugins/3-0#registering-plugins
2. move constructor init to method hook `init` for manually controlling loading on document ready
example for vue:
```ts
import { defineComponent, onMounted } from 'vue'
import { GoogleAuth } from '@reslear/capacitor-google-auth'
export default defineComponent({
setup() {
onMounted(() => {
GoogleAuth.init()
})
const logIn = async () => {
const response = await GoogleAuth.signIn()
console.log(response)
}
return {
logIn
}
}
})
```
=> refactor(web): registering plugins and lazy loading

android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java, ios/Plugin/Plugin.m, ios/Plugin/Plugin.swift
no need check platform: 
```ts
const platform = Capacitor.getPlatform()
if (platform === "web") {
GoogleAuth.init();
}
```
only 
```ts
GoogleAuth.init();
```
TODO:
=> refactor: `init` only for web, no check platform

ios/Plugin/Plugin.swift
Resolves #144 
Unfortunately, the new Google Sign-In SDK shows 2 sign-in prompts if you request additional scopes, but there's no way around that at this time.
=> request additional scopes if necessary

android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java, ios/Plugin/Plugin.swift
In order to properly react to the situation where a user cancels the flow, I added the status code to the Android implementation. The iOS returns the same message in case the user cancels the flow: `"The user canceled the sign-in flow."`
For me this is the last step in order to make this plugin a full replacement for the [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) which also returns the status code.
=> refactor(android): separate messages for signin exception

ios/Plugin/Plugin.swift
Subsequent calls of GoogleAuth.signIn() now return the user object. This is useful when restoring a previous sign in. I use this to fetch a new token that I can then submit to Amazon Cognito Federated Identity pools.
Also added error handling.
This fixes #69 as `let googleUser = await Plugins.GoogleAuth.signIn(null) as any;` hangs due to nothing being returned.
My first PR :)
=> ios return user when restorePreviousSignIn()

README.md
Hello,
For android, this.init() has been depreciated for a while and is not even usable in the latest capacitor.
I've updated the readme with the new way to add plug-ins.
=> Update android plugin instructions

package-lock.json, package.json
Fixing peerDependencies to letting users to migrate Capacitor 5
=> Fix peerDependencies for capacitor migration tool

android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java
This fixes the Android `signOut()` method resolving before the sign-out task is completed.
This causes a race condition where the user is actually logged out but on the next login attempt, the previous account is used instead of showing the account picker.
=> Fix #272, #55

android/src/androidTest/java/com/getcapacitor/android/ExampleInstrumentedTest.java, package.json
I ran into an issue after upgrading to capacitor 5: I could not build my project anymore, because the tests from this project (which I depend on) would not compile. A recent upgrade to androidx moved some stuff around. Furthermore, the error is in a test stub, which I of course, as a consumer, do not need.
This PR: 
- fixes the test stub so it compiles
- excludes the android tests from the npm package
- Note: I did *not* exclude the iOS tests, as I do not have a Mac at hand, so I cannot verify it could cause issues to exclude the tests
=> Port android test stubs to capacitor 5, and exclude them from npm package

README.md, android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java
Hi,
Thanks for you work on the plugin. It's awesome.
I've created a refresh function to return the accessToken and idToken for Android users.
Both IOS and Web have working refresh methods.
Can you guide me to what documentation you like me to contribute for this commit?
=> Android refresh method 

ios/Plugin/Plugin.swift, ios/Podfile, ios/Podfile.lock
GoogleSignIn-iOS 6.0 disabled requesting additional scopes in sign in. This plugin's current workaround results in a very weird UX (user gets prompted to sign in and immediately after signing in gets prompted for additional scopes) [VIDEO](https://github.com/google/GoogleSignIn-iOS/issues/23#issuecomment-933015131). 
GoogleSignIn-iOS 6.2 restores the functionality of requesting scopes at signIn, fixing the issue.
https://github.com/google/GoogleSignIn-iOS/issues/23#issuecomment-933015131)).
=> Bump ios GoogleSignIn to 6.2.4 (Allows requesting scopes during initial signIn)

android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java, src/definitions.ts
Google SignIn result return "displayName" (Basically full name) but the User container property "name" which is never populated. 
Ref: https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/2b73c096f894ad27b5c0c06ca704d4c4c408d2d0/android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java#L116 
closes https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/73
=> refactor: deprecate `displayName`, use `name` property (Android)

src/definitions.ts, src/web.ts
=> make initialize return a Promise

ios/Plugin/Plugin.swift
Fixes #334 
Please review, I'm not familiar with Swift - but deprecation warnings do not show anymore
=> Replace deprecated usage of getConfig method on iOS

README.md
Fixes #344
This reverts changes related to capacitor 6 requirement added in https://github.com/CodetrixStudio/CapacitorGoogleAuth/commit/cdeb575c24bab478a6ce02022a2e22bd69e040a1
It may be re-added back once this plugin requires, (or is compatible with) Capacitor v6
=> Revert capacitor 6 requirement in readme

README.md
This update helps to understand how to set ClientID properly as this change in capacitor 6
=> Update README.md for changes introduced in #269

ios/Plugin/Plugin.swift
The `signOut` subroutine within `Plugin.swift` sometimes causes an app crash.
This is due to the function invoking the `signOut` method on `self.googleSignIn` when `self.googleSignIn` is `nil`.
=> Fix nil error & subsequent app crash

tsconfig.json
This was a particular bug
In my environment I use [nx](https://nx.dev/) to orchestrate my monorepo and I'm using capacitor with [@nxext/capacitor](https://nxext.github.io/nx-extensions-ionic/docs/ionic-react/capacitor.html) for the capacitor
The particular problem I'm having is that my environment is already on typescript 5 and that caused conflicts, this is also related to the installation and that kind of thing.
If this PR can't be accepted for some reason, I can try to host this as a fork or something, but I think it would be nice to keep everything together
=> Updating tsconfig to skip lib check

README.md
It seems our warning was not clear for people, so I added more context to try to show we did our best to continue this plugin in a new repo
=> Update README.md with explain of why switching plugin + migration guide
